# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pypyodbc as p
from PyQt5.QtWidgets import QApplication, QStackedWidget, QDialog



con = p.connect('DRIVER={SQL Server};SERVER=vm-as35.staff.corp.local;'
                'DATABASE=db_Skroba;UID=student;PWD=sql2020')


class Ui_Form(QDialog):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1854, 963)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 170, 1800, 900))
        self.tableWidget.setMinimumSize(QtCore.QSize(1500, 900))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalScrollBar()
        self.tableWidget.horizontalScrollMode()
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(620, 0, 671, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(60, 110, 251, 50))
        self.comboBox.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(320, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1290, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1550, 110, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(590, 118, 689, 31))
        self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit.setToolTip("Записывать даные в таблицу нужно',', а формат даты: 'YYYY-MM-DD' ")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.14286pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">CAR RENTAL</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Form", "Таблицы"))
        self.comboBox.setItemText(2, _translate("Form", "Bill"))
        self.comboBox.setItemText(1, _translate("Form", "Client"))
        self.comboBox.setItemText(3, _translate("Form", "Car"))
        self.comboBox.setItemText(4, _translate("Form", "Car_Accident"))
        self.comboBox.setItemText(5, _translate("Form", "Employee"))
        self.comboBox.setItemText(6, _translate("Form", "Make"))
        self.comboBox.setItemText(7, _translate("Form", "Model"))
        self.comboBox.setItemText(8, _translate("Form", "Place"))
        self.comboBox.setItemText(9, _translate("Form", "Resrvation"))
        self.comboBox_2.setItemText(0, _translate("Form", "Запросы"))
        self.comboBox_2.setItemText(1, _translate("Form", "Клиенты с ДТП"))
        self.comboBox_2.setItemText(2, _translate("Form", "Топ 3 авто"))
        self.comboBox_2.setItemText(3, _translate("Form", "Машины “Volkswagen“"))
        self.pushButton.setText(_translate("Form", "INSERT"))
        self.pushButton_2.setText(_translate("Form", "DELETE"))





